server:
  address: ":1234"
  shutdown.timeout: "10s"
  body.limit: "2M"

mongo:
  migrations:
    sourceUrl: "file:./migrations"
    databaseUrl: "mongodb://127.0.0.1:27017/testMigration?connect=single"

minio:
  endpoint: 127.0.0.1:9000
  accessKeyId: AKIAIOSFODNN7EXAMPLE
  secretAccessKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
