server:
  address: ":1234"
  shutdown.timeout: "10s"
  body.limit: "2M"

http:
  idle:
    conns:
      max: 2
    connTimeout: '10s'
  disableCompression: false

mongo:
  migrations:
    databaseUrl: "mongodb://127.0.0.1:27017/testMigration?connect=single"

minio:
  endpoint: 127.0.0.1:9000
  accessKeyId: AKIAIOSFODNN7EXAMPLE
  secretAccessKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

auth:
  url: "http://127.0.0.1:8080/api/profile"
  exclude:
    - "/user.*"
    - "/auth/.*"
    - "/confirm.*"
