server:
  address: ":1234"
  shutdown.timeout: "10s"
  body.limit: "100G"
  url: http://localhost:1234

http:
  idle:
    conns:
      max: 2
    connTimeout: '10s'
  disableCompression: false

mongo:
  migrations:
    databaseUrl: "mongodb://127.0.0.1:27017/testMigration?replicaSet=rs0"
    connect:
      timeout: '10s'

minio:
  endpoint: 127.0.0.1:9000
  accessKeyId: AKIAIOSFODNN7EXAMPLE
  secretAccessKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

auth:
  url: "http://localhost:8070/api/profile"
  exclude:
    - "^/public.*"

limits:
  stat:
    dir: "."
  default:
    per:
      user:
        # 512 megabytes
        max: 536870912