version: '3.7'

services:
  store:
    image: nkonev/blog-store:latest
    deploy:
      labels:
        - traefik.enable=true
        - traefik.backend=blog-store
        - traefik.frontend.rule=PathPrefix:/;Host:store.nkonev.name
        - traefik.port=1234
        - traefik.docker.network=proxy_backend
    ports:
      - 1234:1234
    logging:
      driver: "json-file"
    #      options:
    #        tag: mongo
    networks:
      - traefik_backend
      - backend
    volumes:
      - /host/etc/config.yml:/etc/config.yml
    command: ["-config=/etc/config.yml"]
  mongo:
    image: mongo:4.1.7
    hostname: mongo
#    ports:
#      - 27017:27017
    volumes:
      - mongo_prod_blog_store_data_dir:/data/db
    logging:
      driver: "json-file"
    #      options:
    #        tag: mongo
    networks:
      - backend
  minio:
    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
    hostname: minio
#    ports:
#      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      # multipart temp store on disk (/tmp is in mem in host centos)
      - /var/tmp/blog-store:/tmp
      - /mnt/minio/data:/data
    command: ["server", "/data"]
    logging:
      driver: "json-file"
#      options:
#        tag: minio
    networks:
      - backend

volumes:
  mongo_prod_blog_store_data_dir:

networks:
  backend:
    driver: overlay
  traefik_backend:
    external: true
    name: proxy_backend
