# This file used for both developer and demo purposes.
# It contains environment
version: '3.2'

services:
  mongo:
    image: mongo:4.2.0-bionic
    hostname: mongo
    container_name: mongo-blog-storage
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_blog_storage_data_dir:/data/db
      - ./docker/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: ["--replSet", "rs0"]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
  minio:
    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
    hostname: minio
    container_name: minio-blog-storage
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - minio_data:/data
    command: ["server", "/data"]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

volumes:
  mongo_blog_storage_data_dir:
  minio_data: