version: '3.7'

services:
  store:
    image: nkonev/blog-store:latest
    logging:
      driver: "json-file"
    networks:
      - traefik_backend

  mongo:
    image: mongo:4.1.7
    hostname: mongo
    container_name: mongo-blog-store
    ports:
      - 27017:27017
    volumes:
      - mongo_prod_blog_store_data_dir:/data/db
      driver: "json-file"
  #      options:
  #        tag: mongo
  minio:
    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
    hostname: minio
    container_name: minio-blog-store
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - minio_prod_blog_store_data_dir:/data
    command: ["server", "/data"]
    logging:
      driver: "json-file"
#      options:
#        tag: minio

volumes:
  mongo_prod_blog_store_data_dir:
  minio_prod_blog_store_data_dir:

networks:
  traefik_backend:
    external: true
    name: proxy_backend
